// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need session-level Postgres features PgBouncer's transaction
    // pooling mode doesn't support, so the CLI talks to Neon directly.
    url: process.env["DIRECT_URL"],
  },
});
